import type { UpgradeDef } from '@/engine/types'

/** Ordered by era, then by cost. The UI shows only unlocked, unbought ones. */
export const UPGRADES: UpgradeDef[] = [
  /* ---------------- Era 1 — Dead Core ---------------- */
  {
    id: 'e1-resonance-casing',
    name: 'Resonance Casing',
    blurb: 'The taps stop fighting the rock and start using it.',
    era: 'dead-core',
    cost: { energy: 250 },
    effects: [{ kind: 'buildingMult', building: 'core-tap', mult: 2 }],
    unlock: { kind: 'buildingCount', building: 'core-tap', count: 10 },
  },
  {
    id: 'e1-vent-insulation',
    name: 'Vent Insulation',
    blurb: 'Heat that used to escape now has nowhere to go but through you.',
    era: 'dead-core',
    cost: { energy: 1_600 },
    effects: [{ kind: 'buildingMult', building: 'thermal-vent', mult: 2 }],
    unlock: { kind: 'buildingCount', building: 'thermal-vent', count: 5 },
  },
  {
    id: 'e1-harmonic-tap',
    name: 'Harmonic Tap',
    blurb: 'Every tap pulls on the same beat. The core answers louder.',
    era: 'dead-core',
    cost: { energy: 6_000 },
    effects: [{ kind: 'buildingMult', building: 'core-tap', mult: 2.5 }],
    unlock: { kind: 'buildingCount', building: 'core-tap', count: 30 },
  },
  {
    id: 'e1-grid-synchrony',
    name: 'Grid Synchrony',
    blurb: 'Nothing new is built. Everything simply stops wasting itself.',
    era: 'dead-core',
    cost: { energy: 12_000 },
    effects: [{ kind: 'globalMult', mult: 1.15 }],
    unlock: { kind: 'lifetime', resource: 'energy', amount: 8_000 },
  },
  {
    id: 'e1-superheated-flow',
    name: 'Superheated Flow',
    blurb: 'Past the point where the rock behaves like rock.',
    era: 'dead-core',
    cost: { energy: 30_000 },
    effects: [{ kind: 'buildingMult', building: 'thermal-vent', mult: 2.5 }],
    unlock: { kind: 'buildingCount', building: 'thermal-vent', count: 25 },
  },
  {
    id: 'e1-containment-lattice',
    name: 'Containment Lattice',
    blurb: 'The reaction is no longer merely survivable.',
    era: 'dead-core',
    cost: { energy: 80_000 },
    effects: [{ kind: 'buildingMult', building: 'generator', mult: 2.5 }],
    unlock: { kind: 'buildingCount', building: 'generator', count: 10 },
  },
  {
    id: 'e1-overclocked-core',
    name: 'Overclocked Core',
    blurb: 'The safety margin was the last thing left to spend.',
    era: 'dead-core',
    cost: { energy: 250_000 },
    effects: [{ kind: 'resourceMult', resource: 'energy', mult: 1.25 }],
    unlock: { kind: 'buildingCount', building: 'generator', count: 25 },
  },

  /* ---------------- Era 2 — First Matter ---------------- */
  {
    id: 'e2-cold-condensation',
    name: 'Cold Condensation',
    blurb: 'Matter forms more willingly when nothing is rushing it.',
    era: 'first-matter',
    cost: { matter: 4_000 },
    effects: [{ kind: 'buildingMult', building: 'condenser', mult: 2.5 }],
    unlock: { kind: 'buildingCount', building: 'condenser', count: 10 },
  },
  {
    id: 'e2-diamond-bits',
    name: 'Diamond Bits',
    blurb: 'The crust stops being an obstacle and becomes a schedule.',
    era: 'first-matter',
    cost: { matter: 45_000 },
    effects: [{ kind: 'buildingMult', building: 'drill', mult: 2.5 }],
    unlock: { kind: 'buildingCount', building: 'drill', count: 10 },
  },
  {
    id: 'e2-standardised-parts',
    name: 'Standardised Parts',
    blurb: 'Every drill is the same drill. Nobody builds bespoke anymore.',
    era: 'first-matter',
    cost: { matter: 140_000 },
    effects: [{ kind: 'costReduction', building: 'drill', factor: 0.92 }],
    unlock: { kind: 'buildingCount', building: 'drill', count: 20 },
  },
  {
    id: 'e2-flux-additives',
    name: 'Flux Additives',
    blurb: 'The impurities were the whole problem. They are gone.',
    era: 'first-matter',
    cost: { alloy: 5_000 },
    effects: [{ kind: 'buildingMult', building: 'smelter', mult: 3 }],
    unlock: { kind: 'buildingCount', building: 'smelter', count: 8 },
  },
  {
    id: 'e2-lattice-compression',
    name: 'Lattice Compression',
    blurb: 'More world per unit of world.',
    era: 'first-matter',
    cost: { matter: 500_000 },
    effects: [{ kind: 'buildingMult', building: 'condenser', mult: 3 }],
    unlock: { kind: 'buildingCount', building: 'condenser', count: 30 },
  },
  {
    id: 'e2-matter-recompiler',
    name: 'Matter Recompiler',
    blurb: 'Waste is re-read as input. There is no waste.',
    era: 'first-matter',
    cost: { matter: 1_800_000 },
    effects: [{ kind: 'resourceMult', resource: 'matter', mult: 1.3 }],
    unlock: { kind: 'lifetime', resource: 'matter', amount: 1_200_000 },
  },
  {
    id: 'e2-seismic-charting',
    name: 'Seismic Charting',
    blurb: 'You know where everything is now. All of it.',
    era: 'first-matter',
    cost: { matter: 4_000_000 },
    effects: [{ kind: 'buildingMult', building: 'drill', mult: 3 }],
    unlock: { kind: 'buildingCount', building: 'drill', count: 35 },
  },
  {
    id: 'e2-industrial-symmetry',
    name: 'Industrial Symmetry',
    blurb: 'Every process now feeds a process that feeds it back.',
    era: 'first-matter',
    cost: { matter: 2_500_000, alloy: 30_000 },
    effects: [{ kind: 'globalMult', mult: 1.2 }],
    unlock: { kind: 'buildingCount', building: 'smelter', count: 20 },
  },

  /* ---------------- Era 3 — Machines ---------------- */
  {
    id: 'e3-swarm-logic',
    name: 'Swarm Logic',
    blurb: 'They coordinate without being told to. Nobody wrote that part.',
    era: 'machines',
    cost: { alloy: 45_000 },
    effects: [{ kind: 'buildingMult', building: 'assembler', mult: 3 }],
    unlock: { kind: 'buildingCount', building: 'assembler', count: 10 },
  },
  {
    id: 'e3-continental-casting',
    name: 'Continental Casting',
    blurb: 'Pour once. Wait a week. Remove the mountain range.',
    era: 'machines',
    cost: { alloy: 160_000 },
    effects: [{ kind: 'buildingMult', building: 'foundry', mult: 3 }],
    unlock: { kind: 'buildingCount', building: 'foundry', count: 8 },
  },
  {
    id: 'e3-orbital-mirrors',
    name: 'Orbital Mirrors',
    blurb: 'Sunlight, redirected, arrives where it is useful instead of where it fell.',
    era: 'machines',
    cost: { alloy: 400_000 },
    effects: [{ kind: 'buildingMult', building: 'orbital-collector', mult: 3 }],
    unlock: { kind: 'buildingCount', building: 'orbital-collector', count: 8 },
  },
  {
    id: 'e3-recursive-tooling',
    name: 'Recursive Tooling',
    blurb: 'The tools that build the tools have started improving themselves.',
    era: 'machines',
    cost: { alloy: 900_000 },
    effects: [{ kind: 'buildingMult', building: 'assembler', mult: 3.5 }],
    unlock: { kind: 'buildingCount', building: 'assembler', count: 30 },
  },
  {
    id: 'e3-machine-consensus',
    name: 'Machine Consensus',
    blurb: 'A decision was reached. You were informed afterwards.',
    era: 'machines',
    cost: { alloy: 1_400_000 },
    effects: [{ kind: 'globalMult', mult: 1.35 }],
    unlock: { kind: 'lifetime', resource: 'alloy', amount: 1_000_000 },
  },
  {
    id: 'e3-alloy-transmutation',
    name: 'Alloy Transmutation',
    blurb: 'The distinction between matter and alloy is now a formality.',
    era: 'machines',
    cost: { alloy: 2_200_000 },
    effects: [{ kind: 'resourceMult', resource: 'alloy', mult: 1.4 }],
    unlock: { kind: 'lifetime', resource: 'alloy', amount: 1_700_000 },
  },
  {
    id: 'e3-temporal-pre-echo',
    name: 'Temporal Pre-Echo',
    blurb: 'Output arrives fractionally before the order to produce it. Nobody is comfortable.',
    era: 'machines',
    cost: { alloy: 3_200_000 },
    effects: [{ kind: 'globalMult', mult: 1.5 }],
    unlock: { kind: 'lifetime', resource: 'alloy', amount: 2_500_000 },
  },
]

export const UPGRADES_BY_ID: Record<string, UpgradeDef> = Object.fromEntries(
  UPGRADES.map((u) => [u.id, u]),
)
